#
# Basic settings.
#
url: ""
baseurl: "/"
title: Es Mentira
description: "\"Nadie miente cuando nadie escucha\" - James Beattie"
avatar: /assets/img/logo.png
language: es

#
# Icons
#
icons:
  rss: true
  email:
  bitbucket:
  twitter: esmentiraorg
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin:  # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
disqus:

#
# Localizations.
#
str_next: Siguiente
str_prev: Anterior
str_read_more: Leer más...
str_search: Buscar
str_recent_posts: Publicaciones recientes
str_show_all_posts: Mostrar todas las publicaciones

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: false   # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url: http://qckanemoto.github.io/jekyll-qck-theme/assets/img/ogp.png
  fb:
  admin: # facebook admin id
  app_id: # facebook application id

#
# Plugins.
#
plugins:
  - jekyll-paginate

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

# markdown: redcarpet
# redcarpet:
#   extensions: ["autolink", "fenced_code_blocks", "strikethrough", "superscript", "with_toc_data", "tables", "footnotes", "no_intra_emphasis"]
highlighter: pygments

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
